# Generated by Django 4.2.7 on 2023-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
