# Generated by Django 4.2.7 on 2023-12-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
