# Generated by Django 4.2.7 on 2023-12-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
